### ISSUE TITLE
Vote dead because of 1.12-pre2's deprecation

### ISSUE THREAD

**Issue by TNTUP** [RabidCrab/Minecraft.Vote#4]
[00:47:56 INFO]: [Vote] Enabling Vote v1.11
[00:47:56 ERROR]: Error occurred while enabling Vote v1.11 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
        at me.RabidCrab.Vote.ConfigAccessor.reloadConfig(ConfigAccessor.java:63) ~[?:?]
        at me.RabidCrab.Vote.ConfigAccessor.getConfig(ConfigAccessor.java:70) ~[?:?]
        at me.RabidCrab.Vote.Vote.onEnable(Vote.java:45) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12-pre2.jar:git-Spigot-1ffab67-3ecbb59]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-3ecbb59]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-3ecbb59]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) [PlugMan.jar:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-3ecbb59]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-3ecbb59]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:643) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-3ecbb59]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1365) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-3ecbb59]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1200) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-3ecbb59]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-3ecbb59]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-3ecbb59]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-3ecbb59]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-3ecbb59]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-3ecbb59]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-3ecbb59]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-3ecbb59]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-3ecbb59]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

Take your time, was just to notify you if you're aware of 1.12-pre2's release :x

**Comment by TNTUP** [comment]
I solved it by myself :)
