### ISSUE TITLE
1.12 error :)

### ISSUE THREAD

**Issue by scabbed** [RabidCrab/Minecraft.Vote#6]
Hello, testing with the last 1.12 spigot build

thanks for help

`[17:12:09] [Server thread/INFO]: [Vote] Enabling Vote v1.903
[17:12:09] [Server thread/ERROR]: Error occurred while enabling Vote v1.903 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
	at me.RabidCrab.Vote.ConfigAccessor.reloadConfig(ConfigAccessor.java:63) ~[?:?]
	at me.RabidCrab.Vote.ConfigAccessor.getConfig(ConfigAccessor.java:70) ~[?:?]
	at me.RabidCrab.Vote.Vote.onEnable(Vote.java:47) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Spigot-stb1.11.jar:git-Spigot-5b19044-bb4ae3b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Spigot-stb1.11.jar:git-Spigot-5b19044-bb4ae3b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [Spigot-stb1.11.jar:git-Spigot-5b19044-bb4ae3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [Spigot-stb1.11.jar:git-Spigot-5b19044-bb4ae3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [Spigot-stb1.11.jar:git-Spigot-5b19044-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [Spigot-stb1.11.jar:git-Spigot-5b19044-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [Spigot-stb1.11.jar:git-Spigot-5b19044-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [Spigot-stb1.11.jar:git-Spigot-5b19044-bb4ae3b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [Spigot-stb1.11.jar:git-Spigot-5b19044-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [Spigot-stb1.11.jar:git-Spigot-5b19044-bb4ae3b]
	at java.lang.Thread.run(Thread.java:748) `[?:1.8.0_131]``

**Comment by RabidCrab** [comment]
I updated Vote to 1.12_01 a day after this was posted. You can find the latest version on https://dev.bukkit.org/projects/vote/ or https://www.spigotmc.org/resources/vote.32471/
